# Generated by Django 5.2.7 on 2025-10-14 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh mobile number (e.g., 01712345678 or +8801712345678)', regex='^(\\+88)?01[3-9]\\d{8}$')], verbose_name='Mobile Number'),
        ),
    ]
